**2026 NBA Playoff Finals (San Antonio Spurs vs New York Knicks) Prediction**

We'll be using dataset from Kaggle to make a prediction on who will be winning the 2026 NBA Finals.

In [3]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.5.20)

In [4]:
import kagglehub

path = kagglehub.dataset_download(
    "eoinamoore/historical-nba-data-and-player-box-scores"
)

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/eoinamoore/historical-nba-data-and-player-box-scores/511.archive...

100%|██████████| 1.03G/1.03G [00:06<00:00, 164MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/eoinamoore/historical-nba-data-and-player-box-scores/versions/511

In [5]:
import os

os.listdir(path)

['TeamStatistics.csv',
 'PlayByPlay.parquet',
 'PlayerStatisticsExtended.csv',
 'LeagueSchedule24_25.csv',
 'LeagueSchedule25_26.csv',
 'PlayerStatistics.csv',
 'Games.csv',
 'TeamHistories.csv',
 'Players.csv',
 'TeamStatisticsExtended.csv']

In [6]:
#Obtaining the datasets using pandas
import pandas as pd

team_stats = pd.read_csv(os.path.join(path, "TeamStatistics.csv"))
games = pd.read_csv(os.path.join(path, "Games.csv"))

/tmp/ipykernel_6746/2179093408.py:5: DtypeWarning: Columns (12,14,15,18,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  games = pd.read_csv(os.path.join(path, "Games.csv"))

In [7]:
#Checking for team_stats
team_stats.head()

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
0,42500404,2026-06-10 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,0,0.0,...,NBA Finals,Game 4,4.0,2.0,8.0,1.0,NaN,NaN,NaN,2026-06-10 20:30:00
1,42500404,2026-06-10 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,1.0,...,NBA Finals,Game 4,4.0,3.0,14.0,2.0,NaN,NaN,NaN,2026-06-10 20:30:00
2,42500403,2026-06-08 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,0.0,...,NBA Finals,Game 3,3.0,3.0,10.0,0.0,NaN,NaN,NaN,2026-06-08 20:30:00
3,42500403,2026-06-08 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,0,1.0,...,NBA Finals,Game 3,3.0,2.0,11.0,0.0,NaN,NaN,NaN,2026-06-08 20:30:00
4,42500402,2026-06-05 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,1,0.0,...,NBA Finals,Game 2,2.0,2.0,11.0,0.0,NaN,NaN,NaN,2026-06-05 20:30:00

In [8]:
#Checking for games
games.head()

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,...,gameLabel,gameSubLabel,seriesGameNumber,attendance,arenaId,arenaName,arenaCity,arenaState,officials,gameDate
0,42500404,2026-06-10 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,107,106,...,NBA Finals,Game 4,Game 4,19812.0,30,Madison Square Garden,New York,NY,"Courtney Kirkland, Zach Zarba, James Williams,...",2026-06-10 20:30:00
1,42500403,2026-06-08 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,111,115,...,NBA Finals,Game 3,Game 3,19812.0,30,Madison Square Garden,New York,NY,"Marc Davis, John Goble, Curtis Blair, Nick Buc...",2026-06-08 20:30:00
2,42500402,2026-06-05 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,104,105,...,NBA Finals,Game 2,Game 2,19014.0,1000118,Frost Bank Center,San Antonio,TX,"Tony Brothers, Josh Tiven, Mitchell Ervin, Tyl...",2026-06-05 20:30:00
3,42500401,2026-06-03 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,95,105,...,NBA Finals,Game 1,Game 1,18835.0,1000118,Frost Bank Center,San Antonio,TX,"James Capers, JB DeRosa, Scott Foster, Sean Wr...",2026-06-03 20:30:00
4,42500317,2026-05-30 20:00:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,103,111,...,West Conf. Finals,Game 7,Game 7,18203.0,1000052,Paycom Center,Oklahoma City,OK,"Marc Davis, John Goble, Josh Tiven, Mitchell E...",2026-05-30 20:00:00

In [9]:
#Checking to see if the datasets can be merged
shared_columns = set(team_stats.columns).intersection(set(games.columns))
shared_columns

{'gameDate',
 'gameDateTimeEst',
 'gameId',
 'gameLabel',
 'gameSubLabel',
 'gameType',
 'seriesGameNumber'}

In [11]:
#Merged dataset using gameID
merged_df = pd.merge(team_stats, games, on='gameId')

In [12]:
merged_df

,gameId,gameDateTimeEst_x,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel_y,gameSubLabel_y,seriesGameNumber_y,attendance,arenaId,arenaName,arenaCity,arenaState,officials,gameDate_y
0,42500404,2026-06-10 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,0,0.0,...,NBA Finals,Game 4,Game 4,19812.0,30,Madison Square Garden,New York,NY,"Courtney Kirkland, Zach Zarba, James Williams,...",2026-06-10 20:30:00
1,42500404,2026-06-10 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,1.0,...,NBA Finals,Game 4,Game 4,19812.0,30,Madison Square Garden,New York,NY,"Courtney Kirkland, Zach Zarba, James Williams,...",2026-06-10 20:30:00
2,42500403,2026-06-08 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,0.0,...,NBA Finals,Game 3,Game 3,19812.0,30,Madison Square Garden,New York,NY,"Marc Davis, John Goble, Curtis Blair, Nick Buc...",2026-06-08 20:30:00
3,42500403,2026-06-08 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,0,1.0,...,NBA Finals,Game 3,Game 3,19812.0,30,Madison Square Garden,New York,NY,"Marc Davis, John Goble, Curtis Blair, Nick Buc...",2026-06-08 20:30:00
4,42500402,2026-06-05 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,1,0.0,...,NBA Finals,Game 2,Game 2,19014.0,1000118,Frost Bank Center,San Antonio,TX,"Tony Brothers, Josh Tiven, Mitchell Ervin, Tyl...",2026-06-05 20:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146553,24600076,1946-12-05 19:00:00,New York,Knicks,1610612752,Philadelphia,Warriors,1610612744,0,0.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1946-12-05 19:00:00
146554,24600063,1946-11-30 19:00:00,Philadelphia,Warriors,1610612744,New York,Knicks,1610612752,0,0.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1946-11-30 19:00:00
146555,24600063,1946-11-30 19:00:00,New York,Knicks,1610612752,Philadelphia,Warriors,1610612744,1,1.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1946-11-30 19:00:00
146556,24600052,1946-11-26 19:00:00,Boston,Celtics,1610612738,Philadelphia,Warriors,1610612744,0,0.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1946-11-26 19:00:00
146557,24600052,1946-11-26 19:00:00,Philadelphia,Warriors,1610612744,Boston,Celtics,1610612738,1,1.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1946-11-26 19:00:00

In [13]:
#Checking on the shape of the merged dataset and inital dataset
print("Team stats shape:", team_stats.shape)
print("Games shape:", games.shape)
print("Merged shape:", merged_df.shape)

Team stats shape: (146558, 59)
Games shape: (73278, 23)
Merged shape: (146558, 81)

In [14]:
team_stats.shape[0] == merged_df.shape[0]

True

In [15]:
#Checking for null values in the dataset
merged_df.isna().sum().sort_values(ascending=False).head(30)

coachId                146558
gameSubtype            146410
gameSubLabel_y         145904
ot2Points              145452
arenaState             143776
attendance             143774
officials              143758
arenaCity              143758
arenaName              143758
ot1Points              138742
otAllPoints            138738
seed                   138688
gameLabel_y            138474
seriesGameNumber_x     137682
gameSubLabel_x         137332
gameLabel_x            137250
seriesGameNumber_y     134914
q4Points                 7900
q3Points                 7898
q2Points                 7864
q1Points                 7848
reboundsTeam             7590
gameType_x               7590
turnoversTeam            7590
pointsFromTurnovers      7310
biggestLead              7310
benchPoints              7310
leadChanges              7310
biggestScoringRun        7310
pointsSecondChance       7310
dtype: int64

In [16]:
#Checking to see which columns are useful for the model dataset
merged_df.columns

Index(['gameId', 'gameDateTimeEst_x', 'teamCity', 'teamName', 'teamId',
       'opponentTeamCity', 'opponentTeamName', 'opponentTeamId', 'home', 'win',
       'teamScore', 'opponentScore', 'assists', 'blocks', 'steals',
       'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalsPercentage',
       'threePointersAttempted', 'threePointersMade',
       'threePointersPercentage', 'freeThrowsAttempted', 'freeThrowsMade',
       'freeThrowsPercentage', 'reboundsDefensive', 'reboundsOffensive',
       'reboundsTotal', 'foulsPersonal', 'turnovers', 'plusMinusPoints',
       'numMinutes', 'q1Points', 'q2Points', 'q3Points', 'q4Points',
       'benchPoints', 'biggestLead', 'biggestScoringRun', 'leadChanges',
       'pointsFastBreak', 'pointsFromTurnovers', 'pointsInThePaint',
       'pointsSecondChance', 'timesTied', 'timeoutsRemaining', 'seasonWins',
       'seasonLosses', 'coachId', 'gameType_x', 'gameLabel_x',
       'gameSubLabel_x', 'seriesGameNumber_x', 'seed', 'reboundsTeam',
       'turnoversTeam', 'ot1Points', 'ot2Points', 'otAllPoints', 'gameDate_x',
       'gameDateTimeEst_y', 'hometeamCity', 'hometeamName', 'hometeamId',
       'awayteamCity', 'awayteamName', 'awayteamId', 'homeScore', 'awayScore',
       'winner', 'gameType_y', 'gameSubtype', 'gameLabel_y', 'gameSubLabel_y',
       'seriesGameNumber_y', 'attendance', 'arenaId', 'arenaName', 'arenaCity',
       'arenaState', 'officials', 'gameDate_y'],
      dtype='object')

In [17]:
model_df = merged_df[
    [
        "gameId",
        "gameDate_x",
        "teamCity",
        "teamName",
        "opponentTeamCity",
        "opponentTeamName",
        "home",
        "win",
        "teamScore",
        "opponentScore",
        "assists",
        "blocks",
        "steals",
        "fieldGoalsAttempted",
        "fieldGoalsMade",
        "fieldGoalsPercentage",
        "threePointersAttempted",
        "threePointersMade",
        "threePointersPercentage",
        "freeThrowsAttempted",
        "freeThrowsMade",
        "freeThrowsPercentage",
        "reboundsDefensive",
        "reboundsOffensive",
        "reboundsTotal",
        "turnovers",
        "plusMinusPoints",
        "q1Points",
        "q2Points",
        "q3Points",
        "q4Points",
        "benchPoints",
        "biggestLead",
        "pointsFastBreak",
        "pointsFromTurnovers",
        "pointsInThePaint",
        "pointsSecondChance",
        "seasonWins",
        "seasonLosses",
        "gameType_x",
        "gameLabel_x",
        "seriesGameNumber_x"
    ]
].copy()

In [18]:
model_df = model_df.rename(columns={
    "gameDate_x": "gameDate",
    "gameType_x": "gameType",
    "gameLabel_x": "gameLabel",
    "seriesGameNumber_x": "seriesGameNumber"
})

In [19]:
model_df.head()

,gameId,gameDate,teamCity,teamName,opponentTeamCity,opponentTeamName,home,win,teamScore,opponentScore,...,biggestLead,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,seasonWins,seasonLosses,gameType,gameLabel,seriesGameNumber
0,42500404,2026-06-10 20:30:00,San Antonio,Spurs,New York,Knicks,0,0.0,106,107,...,29.0,12.0,25.0,28.0,10.0,1.0,3.0,Playoffs,NBA Finals,4.0
1,42500404,2026-06-10 20:30:00,New York,Knicks,San Antonio,Spurs,1,1.0,107,106,...,1.0,13.0,11.0,34.0,14.0,3.0,1.0,Playoffs,NBA Finals,4.0
2,42500403,2026-06-08 20:30:00,New York,Knicks,San Antonio,Spurs,1,0.0,111,115,...,7.0,15.0,7.0,46.0,21.0,2.0,1.0,Playoffs,NBA Finals,3.0
3,42500403,2026-06-08 20:30:00,San Antonio,Spurs,New York,Knicks,0,1.0,115,111,...,12.0,5.0,21.0,44.0,10.0,1.0,2.0,Playoffs,NBA Finals,3.0
4,42500402,2026-06-05 20:30:00,San Antonio,Spurs,New York,Knicks,1,0.0,104,105,...,12.0,11.0,19.0,48.0,9.0,0.0,2.0,Playoffs,NBA Finals,2.0

In [20]:
#Converting the date time column
model_df["gameDate"] = pd.to_datetime(model_df["gameDate"])

In [22]:
#Filter to the 2025-2026 season
season_2026 = model_df[
    (model_df["gameDate"] >= "2025-10-01") &
    (model_df["gameDate"] <= "2026-06-30")
].copy()

In [23]:
season_2026.head()

,gameId,gameDate,teamCity,teamName,opponentTeamCity,opponentTeamName,home,win,teamScore,opponentScore,...,biggestLead,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,seasonWins,seasonLosses,gameType,gameLabel,seriesGameNumber
0,42500404,2026-06-10 20:30:00,San Antonio,Spurs,New York,Knicks,0,0.0,106,107,...,29.0,12.0,25.0,28.0,10.0,1.0,3.0,Playoffs,NBA Finals,4.0
1,42500404,2026-06-10 20:30:00,New York,Knicks,San Antonio,Spurs,1,1.0,107,106,...,1.0,13.0,11.0,34.0,14.0,3.0,1.0,Playoffs,NBA Finals,4.0
2,42500403,2026-06-08 20:30:00,New York,Knicks,San Antonio,Spurs,1,0.0,111,115,...,7.0,15.0,7.0,46.0,21.0,2.0,1.0,Playoffs,NBA Finals,3.0
3,42500403,2026-06-08 20:30:00,San Antonio,Spurs,New York,Knicks,0,1.0,115,111,...,12.0,5.0,21.0,44.0,10.0,1.0,2.0,Playoffs,NBA Finals,3.0
4,42500402,2026-06-05 20:30:00,San Antonio,Spurs,New York,Knicks,1,0.0,104,105,...,12.0,11.0,19.0,48.0,9.0,0.0,2.0,Playoffs,NBA Finals,2.0

In [24]:
#Filter to Spurs and Knicks 2026
spurs_knicks_2026 = season_2026[
    season_2026["teamName"].isin(["San Antonio Spurs", "New York Knicks"]) &
    season_2026["teamCity"].isin(["San Antonio", "New York"])
].copy()

In [25]:
#Check to see if it works
spurs_knicks_2026[
    ["gameDate", "teamCity", "teamName", "opponentTeamCity", "opponentTeamName", "teamScore", "opponentScore", "win"]
].head()

Empty DataFrame
Columns: [gameDate, teamCity, teamName, opponentTeamCity, opponentTeamName, teamScore, opponentScore, win]
Index: []

In [26]:
spurs_vs_knicks = season_2026[
    (
        (season_2026["teamCity"].isin(["San Antonio", "New York"])) &
        (season_2026["opponentTeamCity"].isin(["San Antonio", "New York"])) &
        (season_2026["teamName"].isin(["Spurs", "Knicks"])) &
        (season_2026["opponentTeamName"].isin(["Spurs", "Knicks"]))
    )
].copy()

In [27]:
spurs_vs_knicks[
    [
        "gameDate",
        "teamCity",
        "teamName",
        "opponentTeamCity",
        "opponentTeamName",
        "home",
        "teamScore",
        "opponentScore",
        "win",
        "gameType",
        "gameLabel",
        "seriesGameNumber"
    ]
].sort_values("gameDate")

,gameDate,teamCity,teamName,opponentTeamCity,opponentTeamName,home,teamScore,opponentScore,win,gameType,gameLabel,seriesGameNumber
1882,2025-12-16 20:30:00,San Antonio,Spurs,New York,Knicks,0,113,124,0.0,Emirates NBA Cup,Emirates NBA Cup,NaN
1883,2025-12-16 20:30:00,New York,Knicks,San Antonio,Spurs,1,124,113,1.0,Emirates NBA Cup,Emirates NBA Cup,NaN
1672,2025-12-31 19:00:00,New York,Knicks,San Antonio,Spurs,0,132,134,0.0,Regular Season,NaN,NaN
1673,2025-12-31 19:00:00,San Antonio,Spurs,New York,Knicks,1,134,132,1.0,Regular Season,NaN,NaN
848,2026-03-01 13:00:00,San Antonio,Spurs,New York,Knicks,0,89,114,0.0,Regular Season,NaN,NaN
849,2026-03-01 13:00:00,New York,Knicks,San Antonio,Spurs,1,114,89,1.0,Regular Season,NaN,NaN
6,2026-06-03 20:30:00,New York,Knicks,San Antonio,Spurs,0,105,95,1.0,Playoffs,NBA Finals,1.0
7,2026-06-03 20:30:00,San Antonio,Spurs,New York,Knicks,1,95,105,0.0,Playoffs,NBA Finals,1.0
4,2026-06-05 20:30:00,San Antonio,Spurs,New York,Knicks,1,104,105,0.0,Playoffs,NBA Finals,2.0
5,2026-06-05 20:30:00,New York,Knicks,San Antonio,Spurs,0,105,104,1.0,Playoffs,NBA Finals,2.0
2,2026-06-08 20:30:00,New York,Knicks,San Antonio,Spurs,1,111,115,0.0,Playoffs,NBA Finals,3.0
3,2026-06-08 20:30:00,San Antonio,Spurs,New York,Knicks,0,115,111,1.0,Playoffs,NBA Finals,3.0
0,2026-06-10 20:30:00,San Antonio,Spurs,New York,Knicks,0,106,107,0.0,Playoffs,NBA Finals,4.0
1,2026-06-10 20:30:00,New York,Knicks,San Antonio,Spurs,1,107,106,1.0,Playoffs,NBA Finals,4.0

In [28]:
model_df["team"] = model_df["teamCity"] + " " + model_df["teamName"]
model_df["opponent"] = model_df["opponentTeamCity"] + " " + model_df["opponentTeamName"]

In [29]:
season_2026 = model_df[
    (model_df["gameDate"] >= "2025-10-01") &
    (model_df["gameDate"] <= "2026-06-30")
].copy()

In [30]:
spurs_vs_knicks = season_2026[
    (
        (season_2026["team"].isin(["San Antonio Spurs", "New York Knicks"])) &
        (season_2026["opponent"].isin(["San Antonio Spurs", "New York Knicks"]))
    )
].copy()

In [31]:
features = [
    "home",
    "assists",
    "blocks",
    "steals",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage",
    "reboundsTotal",
    "turnovers",
    "benchPoints",
    "pointsFastBreak",
    "pointsFromTurnovers",
    "pointsInThePaint",
    "pointsSecondChance",
    "seasonWins",
    "seasonLosses"
]

X = model_df[features]
y = model_df["win"]

In [32]:
model_df["win"].value_counts()

win
0.0    73278
1.0    73278
Name: count, dtype: int64

In [35]:
import numpy as np

# Replace infinity values with NaN
model_df = model_df.replace([np.inf, -np.inf], np.nan)

# Keep only rows where both scores exist
model_df = model_df.dropna(subset=["teamScore", "opponentScore"]).copy()

# Create clean win target
model_df["win_binary"] = (model_df["teamScore"] > model_df["opponentScore"]).astype(int)

# Check result
model_df["win_binary"].value_counts()

win_binary
0    73284
1    73274
Name: count, dtype: int64

In [36]:
features = [
    "home",
    "seasonWins",
    "seasonLosses"
]

X = model_df[features]
y = model_df["win_binary"]

In [37]:
# Replace inf values in features
X = X.replace([np.inf, -np.inf], np.nan)

# Fill missing numeric values with median
X = X.fillna(X.median())

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy: 0.6476187227074236
              precision    recall  f1-score   support

           0       0.64      0.65      0.65     14471
           1       0.65      0.65      0.65     14841

    accuracy                           0.65     29312
   macro avg       0.65      0.65      0.65     29312
weighted avg       0.65      0.65      0.65     29312

In [39]:
#Adding a rolling feature
rolling_features = [
    "teamScore",
    "opponentScore",
    "assists",
    "reboundsTotal",
    "turnovers",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage"
]

In [40]:
# Sort by team and date
model_df = model_df.sort_values(["teamCity", "teamName", "gameDate"])

# Create full team name
model_df["team"] = model_df["teamCity"] + " " + model_df["teamName"]

# Stats to convert into rolling averages
rolling_cols = [
    "teamScore",
    "opponentScore",
    "assists",
    "reboundsTotal",
    "turnovers",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage"
]

# Create previous 5-game rolling averages
for col in rolling_cols:
    model_df[f"{col}_last5"] = (
        model_df
        .groupby("team")[col]
        .shift(1)
        .rolling(5)
        .mean()
    )

In [41]:
features = [
    "home",
    "seasonWins",
    "seasonLosses",
    "teamScore_last5",
    "opponentScore_last5",
    "assists_last5",
    "reboundsTotal_last5",
    "turnovers_last5",
    "fieldGoalsPercentage_last5",
    "threePointersPercentage_last5",
    "freeThrowsPercentage_last5"
]

model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy: 0.6510724053548295
              precision    recall  f1-score   support

           0       0.65      0.65      0.65     13962
           1       0.65      0.65      0.65     13826

    accuracy                           0.65     27788
   macro avg       0.65      0.65      0.65     27788
weighted avg       0.65      0.65      0.65     27788

**Checking to see if we can a higher accuracy score**

In [43]:
import pandas as pd
import numpy as np

model_df["gameDate"] = pd.to_datetime(model_df["gameDate"])

model_df["team"] = model_df["teamCity"] + " " + model_df["teamName"]
model_df["opponent"] = model_df["opponentTeamCity"] + " " + model_df["opponentTeamName"]

model_df = model_df.sort_values(["team", "gameDate"])

In [44]:
model_df = model_df.replace([np.inf, -np.inf], np.nan)

model_df = model_df.dropna(subset=["teamScore", "opponentScore"]).copy()

model_df["win_binary"] = (model_df["teamScore"] > model_df["opponentScore"]).astype(int)
model_df["point_diff"] = model_df["teamScore"] - model_df["opponentScore"]

In [45]:
rolling_cols = [
    "teamScore",
    "opponentScore",
    "assists",
    "reboundsTotal",
    "turnovers",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage",
    "steals",
    "blocks",
    "point_diff",
    "win_binary"
]

for col in rolling_cols:
    model_df[f"{col}_last5"] = (
        model_df
        .groupby("team")[col]
        .transform(lambda x: x.shift(1).rolling(5).mean())
    )

In [46]:
features = [
    "home",
    "seasonWins",
    "seasonLosses",
    "teamScore_last5",
    "opponentScore_last5",
    "assists_last5",
    "reboundsTotal_last5",
    "turnovers_last5",
    "fieldGoalsPercentage_last5",
    "threePointersPercentage_last5",
    "freeThrowsPercentage_last5",
    "steals_last5",
    "blocks_last5",
    "point_diff_last5",
    "win_binary_last5"
]

model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_predictions))
print(classification_report(y_test, rf_predictions))

Random Forest Accuracy: 0.662048366201238
              precision    recall  f1-score   support

           0       0.66      0.67      0.67     13888
           1       0.67      0.65      0.66     13900

    accuracy                           0.66     27788
   macro avg       0.66      0.66      0.66     27788
weighted avg       0.66      0.66      0.66     27788

In [48]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_predictions = gb_model.predict(X_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_predictions))
print(classification_report(y_test, gb_predictions))

Gradient Boosting Accuracy: 0.6824168705916223
              precision    recall  f1-score   support

           0       0.68      0.68      0.68     13888
           1       0.68      0.68      0.68     13900

    accuracy                           0.68     27788
   macro avg       0.68      0.68      0.68     27788
weighted avg       0.68      0.68      0.68     27788

In [49]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

log_predictions = log_model.predict(X_test)

print("Logistic Regression:", accuracy_score(y_test, log_predictions))
print("Random Forest:", accuracy_score(y_test, rf_predictions))
print("Gradient Boosting:", accuracy_score(y_test, gb_predictions))

Logistic Regression: 0.6504966172448539
Random Forest: 0.662048366201238
Gradient Boosting: 0.6824168705916223

**Adding Opponent Rolling Feature**

In [50]:
model_df["team"] = model_df["teamCity"] + " " + model_df["teamName"]
model_df["opponent"] = model_df["opponentTeamCity"] + " " + model_df["opponentTeamName"]

model_df["gameDate"] = pd.to_datetime(model_df["gameDate"])
model_df = model_df.sort_values(["team", "gameDate"])

In [51]:
rolling_cols = [
    "teamScore",
    "opponentScore",
    "assists",
    "reboundsTotal",
    "turnovers",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage",
    "steals",
    "blocks",
    "point_diff",
    "win_binary"
]

for col in rolling_cols:
    model_df[f"{col}_last5"] = (
        model_df
        .groupby("team")[col]
        .transform(lambda x: x.shift(1).rolling(5).mean())
    )

In [52]:
opponent_rolling = model_df[
    [
        "gameId",
        "team",
        "teamScore_last5",
        "opponentScore_last5",
        "assists_last5",
        "reboundsTotal_last5",
        "turnovers_last5",
        "fieldGoalsPercentage_last5",
        "threePointersPercentage_last5",
        "freeThrowsPercentage_last5",
        "steals_last5",
        "blocks_last5",
        "point_diff_last5",
        "win_binary_last5"
    ]
].copy()

In [53]:
opponent_rolling = opponent_rolling.rename(columns={
    "team": "opponent",
    "teamScore_last5": "opponent_teamScore_last5",
    "opponentScore_last5": "opponent_opponentScore_last5",
    "assists_last5": "opponent_assists_last5",
    "reboundsTotal_last5": "opponent_reboundsTotal_last5",
    "turnovers_last5": "opponent_turnovers_last5",
    "fieldGoalsPercentage_last5": "opponent_fieldGoalsPercentage_last5",
    "threePointersPercentage_last5": "opponent_threePointersPercentage_last5",
    "freeThrowsPercentage_last5": "opponent_freeThrowsPercentage_last5",
    "steals_last5": "opponent_steals_last5",
    "blocks_last5": "opponent_blocks_last5",
    "point_diff_last5": "opponent_point_diff_last5",
    "win_binary_last5": "opponent_win_binary_last5"
})

In [54]:
model_df = model_df.merge(
    opponent_rolling,
    on=["gameId", "opponent"],
    how="left"
)

In [55]:
model_df["win_pct_last5_diff"] = (
    model_df["win_binary_last5"] - model_df["opponent_win_binary_last5"]
)

model_df["point_diff_last5_diff"] = (
    model_df["point_diff_last5"] - model_df["opponent_point_diff_last5"]
)

model_df["scoring_last5_diff"] = (
    model_df["teamScore_last5"] - model_df["opponent_teamScore_last5"]
)

model_df["rebounds_last5_diff"] = (
    model_df["reboundsTotal_last5"] - model_df["opponent_reboundsTotal_last5"]
)

model_df["turnovers_last5_diff"] = (
    model_df["turnovers_last5"] - model_df["opponent_turnovers_last5"]
)

model_df["three_point_pct_last5_diff"] = (
    model_df["threePointersPercentage_last5"] - model_df["opponent_threePointersPercentage_last5"]
)

In [56]:
features = [
    "home",
    "seasonWins",
    "seasonLosses",
    "win_binary_last5",
    "point_diff_last5",
    "opponent_win_binary_last5",
    "opponent_point_diff_last5",
    "win_pct_last5_diff",
    "point_diff_last5_diff",
    "scoring_last5_diff",
    "rebounds_last5_diff",
    "turnovers_last5_diff",
    "three_point_pct_last5_diff"
]

model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

rf_model.fit(X_train, y_train)

predictions = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy: 0.6827096402047732
              precision    recall  f1-score   support

           0       0.68      0.68      0.68     13870
           1       0.68      0.68      0.68     13868

    accuracy                           0.68     27738
   macro avg       0.68      0.68      0.68     27738
weighted avg       0.68      0.68      0.68     27738

In [59]:
gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_predictions = gb_model.predict(X_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_predictions))
print()
print(classification_report(y_test, gb_predictions))

Gradient Boosting Accuracy: 0.6950753478981903

              precision    recall  f1-score   support

           0       0.70      0.69      0.69     13870
           1       0.69      0.70      0.70     13868

    accuracy                           0.70     27738
   macro avg       0.70      0.70      0.70     27738
weighted avg       0.70      0.70      0.70     27738

**Adding new features**

In [63]:
model_df["season_win_pct"] = (
    model_df["seasonWins"] /
    (model_df["seasonWins"] + model_df["seasonLosses"])
)

In [64]:
features = features + ["season_win_pct"]

In [65]:
model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [66]:
model_df = model_df.sort_values(["team", "gameDate"])

model_df["previous_game_date"] = (
    model_df.groupby("team")["gameDate"].shift(1)
)

model_df["rest_days"] = (
    model_df["gameDate"] - model_df["previous_game_date"]
).dt.days

In [67]:
model_df["rest_days"] = model_df["rest_days"].clip(0, 7)

In [68]:
features = features + ["rest_days"]

In [69]:
model_df["back_to_back"] = (model_df["rest_days"] <= 1).astype(int)

In [70]:
features = features + ["back_to_back"]

In [71]:
features = [
    "home",
    "seasonWins",
    "seasonLosses",
    "season_win_pct",
    "rest_days",
    "back_to_back",

    "win_binary_last5",
    "point_diff_last5",
    "opponent_win_binary_last5",
    "opponent_point_diff_last5",

    "win_pct_last5_diff",
    "point_diff_last5_diff",
    "scoring_last5_diff",
    "rebounds_last5_diff",
    "turnovers_last5_diff",
    "three_point_pct_last5_diff"
]

In [72]:
model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [73]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

gb_model = GradientBoostingClassifier(
    n_estimators=250,
    learning_rate=0.03,
    max_depth=2,
    min_samples_leaf=8,
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_predictions = gb_model.predict(X_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_predictions))
print(classification_report(y_test, gb_predictions))

Gradient Boosting Accuracy: 0.68126757516764
              precision    recall  f1-score   support

           0       0.68      0.68      0.68     13870
           1       0.68      0.69      0.68     13868

    accuracy                           0.68     27738
   macro avg       0.68      0.68      0.68     27738
weighted avg       0.68      0.68      0.68     27738

In [74]:
gb_model = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.025,
    max_depth=2,
    min_samples_leaf=10,
    random_state=42
)

In [75]:
gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=2,
    min_samples_leaf=5,
    random_state=42
)

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [77]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

models = [
    GradientBoostingClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=2,
        min_samples_leaf=5,
        random_state=42
    ),
    GradientBoostingClassifier(
        n_estimators=250,
        learning_rate=0.03,
        max_depth=2,
        min_samples_leaf=8,
        random_state=42
    ),
    GradientBoostingClassifier(
        n_estimators=300,
        learning_rate=0.025,
        max_depth=2,
        min_samples_leaf=10,
        random_state=42
    ),
    GradientBoostingClassifier(
        n_estimators=150,
        learning_rate=0.05,
        max_depth=3,
        min_samples_leaf=10,
        random_state=42
    )
]

for i, model in enumerate(models, start=1):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"Model {i} Accuracy: {acc:.4f}")

Model 1 Accuracy: 0.6912
Model 2 Accuracy: 0.6900
Model 3 Accuracy: 0.6907
Model 4 Accuracy: 0.6976

**Adding more features**

In [78]:
# Team season win percentage
model_df["season_win_pct"] = (
    model_df["seasonWins"] /
    (model_df["seasonWins"] + model_df["seasonLosses"])
)

In [79]:
opponent_record = model_df[
    ["gameId", "team", "seasonWins", "seasonLosses", "season_win_pct"]
].copy()

opponent_record = opponent_record.rename(columns={
    "team": "opponent",
    "seasonWins": "opponent_seasonWins",
    "seasonLosses": "opponent_seasonLosses",
    "season_win_pct": "opponent_season_win_pct"
})

model_df = model_df.merge(
    opponent_record,
    on=["gameId", "opponent"],
    how="left"
)

In [80]:
model_df["season_win_pct_diff"] = (
    model_df["season_win_pct"] - model_df["opponent_season_win_pct"]
)

model_df["season_wins_diff"] = (
    model_df["seasonWins"] - model_df["opponent_seasonWins"]
)

In [81]:
rolling_cols = [
    "teamScore",
    "opponentScore",
    "assists",
    "reboundsTotal",
    "turnovers",
    "fieldGoalsPercentage",
    "threePointersPercentage",
    "freeThrowsPercentage",
    "steals",
    "blocks",
    "point_diff",
    "win_binary"
]

for col in rolling_cols:
    model_df[f"{col}_last10"] = (
        model_df
        .groupby("team")[col]
        .transform(lambda x: x.shift(1).rolling(10).mean())
    )

In [82]:
opponent_rolling_10 = model_df[
    [
        "gameId",
        "team",
        "point_diff_last10",
        "win_binary_last10",
        "teamScore_last10",
        "reboundsTotal_last10",
        "turnovers_last10",
        "threePointersPercentage_last10"
    ]
].copy()

opponent_rolling_10 = opponent_rolling_10.rename(columns={
    "team": "opponent",
    "point_diff_last10": "opponent_point_diff_last10",
    "win_binary_last10": "opponent_win_binary_last10",
    "teamScore_last10": "opponent_teamScore_last10",
    "reboundsTotal_last10": "opponent_reboundsTotal_last10",
    "turnovers_last10": "opponent_turnovers_last10",
    "threePointersPercentage_last10": "opponent_threePointersPercentage_last10"
})

model_df = model_df.merge(
    opponent_rolling_10,
    on=["gameId", "opponent"],
    how="left"
)

In [83]:
model_df["win_pct_last10_diff"] = (
    model_df["win_binary_last10"] - model_df["opponent_win_binary_last10"]
)

model_df["point_diff_last10_diff"] = (
    model_df["point_diff_last10"] - model_df["opponent_point_diff_last10"]
)

model_df["scoring_last10_diff"] = (
    model_df["teamScore_last10"] - model_df["opponent_teamScore_last10"]
)

model_df["rebounds_last10_diff"] = (
    model_df["reboundsTotal_last10"] - model_df["opponent_reboundsTotal_last10"]
)

model_df["turnovers_last10_diff"] = (
    model_df["turnovers_last10"] - model_df["opponent_turnovers_last10"]
)

model_df["three_point_pct_last10_diff"] = (
    model_df["threePointersPercentage_last10"] - model_df["opponent_threePointersPercentage_last10"]
)

In [84]:
features = [
    "home",
    "seasonWins",
    "seasonLosses",
    "season_win_pct",
    "opponent_season_win_pct",
    "season_win_pct_diff",
    "season_wins_diff",
    "rest_days",
    "back_to_back",

    "win_binary_last5",
    "point_diff_last5",
    "opponent_win_binary_last5",
    "opponent_point_diff_last5",
    "win_pct_last5_diff",
    "point_diff_last5_diff",
    "scoring_last5_diff",
    "rebounds_last5_diff",
    "turnovers_last5_diff",
    "three_point_pct_last5_diff",

    "win_binary_last10",
    "point_diff_last10",
    "opponent_win_binary_last10",
    "opponent_point_diff_last10",
    "win_pct_last10_diff",
    "point_diff_last10_diff",
    "scoring_last10_diff",
    "rebounds_last10_diff",
    "turnovers_last10_diff",
    "three_point_pct_last10_diff"
]

In [85]:
model_data = model_df.dropna(subset=features + ["win_binary"]).copy()

X = model_data[features]
y = model_data["win_binary"]

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

gb_model = GradientBoostingClassifier(
    n_estimators=250,
    learning_rate=0.03,
    max_depth=2,
    min_samples_leaf=8,
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_predictions = gb_model.predict(X_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_predictions))
print(classification_report(y_test, gb_predictions))

Gradient Boosting Accuracy: 0.7138459309695411
              precision    recall  f1-score   support

           0       0.71      0.71      0.71     13806
           1       0.71      0.71      0.71     13805

    accuracy                           0.71     27611
   macro avg       0.71      0.71      0.71     27611
weighted avg       0.71      0.71      0.71     27611

In [87]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

hist_model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.03,
    max_leaf_nodes=15,
    min_samples_leaf=20,
    random_state=42
)

hist_model.fit(X_train, y_train)

hist_predictions = hist_model.predict(X_test)

print("Hist Gradient Boosting Accuracy:", accuracy_score(y_test, hist_predictions))
print(classification_report(y_test, hist_predictions))

Hist Gradient Boosting Accuracy: 0.7285502154938249
              precision    recall  f1-score   support

           0       0.73      0.73      0.73     13806
           1       0.73      0.73      0.73     13805

    accuracy                           0.73     27611
   macro avg       0.73      0.73      0.73     27611
weighted avg       0.73      0.73      0.73     27611

**Using spurs_vs_knicks to HistGradientBoosting**

In [89]:
# Recreate spurs_vs_knicks with all calculated features
spurs_vs_knicks = model_df[
    (model_df["gameDate"] >= "2025-10-01") &
    (model_df["gameDate"] <= "2026-06-30")
].copy()

spurs_vs_knicks = spurs_vs_knicks[
    (
        (spurs_vs_knicks["team"].isin(["San Antonio Spurs", "New York Knicks"])) &
        (spurs_vs_knicks["opponent"].isin(["San Antonio Spurs", "New York Knicks"]))
    )
].copy()

# Make sure spurs_vs_knicks has the same features used to train the model
spurs_knicks_data = spurs_vs_knicks.dropna(subset=features).copy()

X_spurs_knicks = spurs_knicks_data[features]

# Predict win/loss
spurs_knicks_data["predicted_win"] = hist_model.predict(X_spurs_knicks)

# Predict win probability
spurs_knicks_data["win_probability"] = hist_model.predict_proba(X_spurs_knicks)[:, 1]

# View results
spurs_knicks_data[
    [
        "gameDate",
        "team",
        "opponent",
        "home",
        "teamScore",
        "opponentScore",
        "win_binary",
        "predicted_win",
        "win_probability"
    ]
].sort_values("gameDate")

,gameDate,team,opponent,home,teamScore,opponentScore,win_binary,predicted_win,win_probability
96753,2025-12-16 20:30:00,New York Knicks,San Antonio Spurs,1,124,113,1,1,0.999149
127197,2025-12-16 20:30:00,San Antonio Spurs,New York Knicks,0,113,124,0,0,0.002095
96761,2025-12-31 19:00:00,New York Knicks,San Antonio Spurs,0,132,134,0,0,0.266477
127205,2025-12-31 19:00:00,San Antonio Spurs,New York Knicks,1,134,132,1,1,0.768190
96789,2026-03-01 13:00:00,New York Knicks,San Antonio Spurs,1,114,89,1,1,0.580610
127232,2026-03-01 13:00:00,San Antonio Spurs,New York Knicks,0,89,114,0,0,0.418871
96825,2026-06-03 20:30:00,New York Knicks,San Antonio Spurs,0,105,95,1,1,0.999099
127273,2026-06-03 20:30:00,San Antonio Spurs,New York Knicks,1,95,105,0,0,0.002525
96826,2026-06-05 20:30:00,New York Knicks,San Antonio Spurs,0,105,104,1,1,0.999056
127274,2026-06-05 20:30:00,San Antonio Spurs,New York Knicks,1,104,105,0,0,0.002459
96827,2026-06-08 20:30:00,New York Knicks,San Antonio Spurs,1,111,115,0,0,0.368689
127275,2026-06-08 20:30:00,San Antonio Spurs,New York Knicks,0,115,111,1,1,0.636757
96828,2026-06-10 20:30:00,New York Knicks,San Antonio Spurs,1,107,106,1,1,0.891141
127276,2026-06-10 20:30:00,San Antonio Spurs,New York Knicks,0,106,107,0,0,0.105466

In [90]:
spurs_knicks_data["win_probability_percent"] = (
    spurs_knicks_data["win_probability"] * 100
).round(2)

spurs_knicks_data[
    [
        "gameDate",
        "team",
        "opponent",
        "home",
        "win_probability_percent",
        "predicted_win"
    ]
].sort_values("gameDate")

,gameDate,team,opponent,home,win_probability_percent,predicted_win
96753,2025-12-16 20:30:00,New York Knicks,San Antonio Spurs,1,99.91,1
127197,2025-12-16 20:30:00,San Antonio Spurs,New York Knicks,0,0.21,0
96761,2025-12-31 19:00:00,New York Knicks,San Antonio Spurs,0,26.65,0
127205,2025-12-31 19:00:00,San Antonio Spurs,New York Knicks,1,76.82,1
96789,2026-03-01 13:00:00,New York Knicks,San Antonio Spurs,1,58.06,1
127232,2026-03-01 13:00:00,San Antonio Spurs,New York Knicks,0,41.89,0
96825,2026-06-03 20:30:00,New York Knicks,San Antonio Spurs,0,99.91,1
127273,2026-06-03 20:30:00,San Antonio Spurs,New York Knicks,1,0.25,0
96826,2026-06-05 20:30:00,New York Knicks,San Antonio Spurs,0,99.91,1
127274,2026-06-05 20:30:00,San Antonio Spurs,New York Knicks,1,0.25,0
96827,2026-06-08 20:30:00,New York Knicks,San Antonio Spurs,1,36.87,0
127275,2026-06-08 20:30:00,San Antonio Spurs,New York Knicks,0,63.68,1
96828,2026-06-10 20:30:00,New York Knicks,San Antonio Spurs,1,89.11,1
127276,2026-06-10 20:30:00,San Antonio Spurs,New York Knicks,0,10.55,0

In [91]:
predicted_game_winners = (
    spurs_knicks_data
    .sort_values(["gameId", "win_probability"], ascending=[True, False])
    .groupby("gameId")
    .head(1)
)

predicted_game_winners[
    [
        "gameDate",
        "team",
        "opponent",
        "home",
        "win_probability_percent"
    ]
].sort_values("gameDate")

,gameDate,team,opponent,home,win_probability_percent
96753,2025-12-16 20:30:00,New York Knicks,San Antonio Spurs,1,99.91
127205,2025-12-31 19:00:00,San Antonio Spurs,New York Knicks,1,76.82
96789,2026-03-01 13:00:00,New York Knicks,San Antonio Spurs,1,58.06
96825,2026-06-03 20:30:00,New York Knicks,San Antonio Spurs,0,99.91
96826,2026-06-05 20:30:00,New York Knicks,San Antonio Spurs,0,99.91
127275,2026-06-08 20:30:00,San Antonio Spurs,New York Knicks,0,63.68
96828,2026-06-10 20:30:00,New York Knicks,San Antonio Spurs,1,89.11

In [92]:
finals_predictions = predicted_game_winners.copy()

knicks_predicted_wins = 3
spurs_predicted_wins = 1

for _, row in finals_predictions.sort_values("gameDate").iterrows():
    if row["team"] == "New York Knicks":
        knicks_predicted_wins += 1
    elif row["team"] == "San Antonio Spurs":
        spurs_predicted_wins += 1

    if knicks_predicted_wins == 4 or spurs_predicted_wins == 4:
        break

print("Predicted Knicks wins:", knicks_predicted_wins)
print("Predicted Spurs wins:", spurs_predicted_wins)

if knicks_predicted_wins == 4:
    print("Predicted Finals Winner: New York Knicks")
elif spurs_predicted_wins == 4:
    print("Predicted Finals Winner: San Antonio Spurs")

Predicted Knicks wins: 4
Predicted Spurs wins: 1
Predicted Finals Winner: New York Knicks

In [93]:
summary_table = predicted_game_winners[
    [
        "gameDate",
        "team",
        "opponent",
        "home",
        "win_probability_percent"
    ]
].copy()

summary_table = summary_table.rename(columns={
    "team": "Predicted Winner",
    "opponent": "Opponent",
    "home": "Home Game",
    "win_probability_percent": "Win Probability (%)"
})

summary_table

,gameDate,Predicted Winner,Opponent,Home Game,Win Probability (%)
127205,2025-12-31 19:00:00,San Antonio Spurs,New York Knicks,1,76.82
96789,2026-03-01 13:00:00,New York Knicks,San Antonio Spurs,1,58.06
96825,2026-06-03 20:30:00,New York Knicks,San Antonio Spurs,0,99.91
96826,2026-06-05 20:30:00,New York Knicks,San Antonio Spurs,0,99.91
127275,2026-06-08 20:30:00,San Antonio Spurs,New York Knicks,0,63.68
96828,2026-06-10 20:30:00,New York Knicks,San Antonio Spurs,1,89.11
96753,2025-12-16 20:30:00,New York Knicks,San Antonio Spurs,1,99.91